### PR TITLE
add php8.2 and add php8.1 formula

### PR DESCRIPTION
**Pull request by it-can**
hopefully this is correct

### CODE REVIEW

**Comment by kabel** [comment]
It's a good start and I'll finish it off tomorrow. It will take several hours to rebuild the 8.1 and 8.2 bottles, so I'll need to split this into several builds to avoid overloading my build boxes and hitting the build timeout.

**Comment by it-can** [comment]
@kabel thanks!

**Comment by kabel** [comment]
Well, this weekend has been unlucky. I've got things running from a fixed up commit at 48a8276914fc55745688d056c36d2cfd665173c8. I tried to get everything to build in one shot/job on my build agents, but the build has triggered kernel panics after 9 hours (first try) and 6 hours (second try) and each time the build agents lost all their work. I'm going to get it one more try today before I split the build into smaller pieces the minimize the risk of lost work. Still hopeful to get the new builds uploaded early this week.

**Comment by it-can** [comment]
> Well, this weekend has been unlucky. I've got things running from a fixed up commit at [48a8276](https://github.com/kabel/homebrew-pecl/commit/48a8276914fc55745688d056c36d2cfd665173c8). I tried to get everything to build in one shot/job on my build agents, but the build has triggered kernel panics after 9 hours (first try) and 6 hours (second try) and each time the build agents lost all their work. I'm going to get it one more try today before I split the build into smaller pieces the minimize the risk of lost work. Still hopeful to get the new builds uploaded early this week.

damn thats a bummer... could a job per pecl extension work or per 6 extensions?

**Comment by kabel** [comment]
Everything but `php-pecl-http` and `php@8.1-pecl-http` integrated into main at a518208d8d8e92e9515c6c16c7ea7dadc635964b.

**Comment by it-can** [comment]
thanks man!

**Pull request closed without merging**
