### PR TITLE
Add memprof-3.0.0 formulas

### PR DESCRIPTION
**Pull request by glensc**
https://pecl.php.net/package/memprof

- [x] judy dependency

cc @kabel

### CODE REVIEW

**Comment by glensc** [comment]
```
checking for judy lib... yes, shared
checking for judy files in default path... not found
configure: error: Please reinstall the judy distribution
```

```
➔ brew search judy
Error: No formulae or casks found for "judy".
```

**Comment by glensc** [comment]
It used to exist in the main brew, but now is removed

I've extracted the last version into my tap:
- https://github.com/glensc/homebrew-tap/pull/16

but I don't think it's possible to add dependencies cross taps, so should add that recipe to this repo?

**Comment by glensc** [comment]
some compile error as well:

```
/private/tmp/phpA7.3-memprof-20210604-9617-1gt1u1w/memprof-3.0.0/memprof.c:984:7: error: use of undeclared identifier 'HAVE_MALLOC_HOOKS'
                if (HAVE_MALLOC_HOOKS && strcmp(MEMPROF_FLAG_NATIVE, flag) == 0) {
                    ^
/private/tmp/phpA7.3-memprof-20210604-9617-1gt1u1w/memprof-3.0.0/memprof.c:1199:66: error: use of undeclared identifier 'HAVE_MALLOC_HOOKS'
        php_info_print_table_header(2, "memprof native malloc support", HAVE_MALLOC_HOOKS ? "Yes" : "No");
                                                                        ^
2 errors generated.
```

**Comment by kabel** [comment]
> but I don't think it's possible to add dependencies cross taps, so should add that recipe to this repo?

It is possible using the fully qualified dependency name: `glensc/tap/judy` , but that approach should be avoided. It left the core because it was/is unmaintained. So it should not be used in a shared context. That said, vendoring the dependency is always an option.  You do that by 
- Declaring the [necessary resource](https://github.com/kabel/homebrew-php-ext/blob/e8a0f0c6ddb068b6f88b031e5add5a1f2277f343/lib/oracle_php_extension_formula.rb#L45-L48)
- [Loading that resource](https://github.com/kabel/homebrew-php-ext/blob/e8a0f0c6ddb068b6f88b031e5add5a1f2277f343/lib/oracle_php_extension_formula.rb#L8) into the Cellar
- Building the loaded resource using the normal build steps as an extension to the `install` function
 (no example since the previous are binary resources, but the gist is chdir to the loaded source and running make/install)

----
I kicked my bottle VMs so they should be running now. But if there are compile errors, those will need to be resolved upstream.

**Comment by glensc** [comment]
can `patch do` have `chdir` as the weird pecl depenency the source is in a subdir?

```diff
diff --git a/Formula/php@7.3-memprof.rb b/Formula/php@7.3-memprof.rb
index e6a1a48..096563e 100644
--- a/Formula/php@7.3-memprof.rb
+++ b/Formula/php@7.3-memprof.rb
@@ -6,4 +6,9 @@ class PhpAT73Memprof < PhpPeclFormula
   url "https://pecl.php.net/get/memprof-3.0.0.tgz"
   sha256 "3ea040f59f828fe6999ffa6ff1a6762a457f5c6af6ccfb1614ace884cc19dd82"
   license "BSD-2-Clause"
+
+    patch do
+      url "https://github.com/arnaud-lb/php-memory-profiler/commit/1ebb467186a7a4dcfc0df0bad2df3a944b9f9349.patch"
+      sha256 "c69264f6467d19f8b0770577f6bdd0c33b558a0eeee3356dd2f46a4d7358b231"
+    end
 end
```

as then I could pull the upstream patch:


or go for embedded patch until they make a release?
- https://docs.brew.sh/Formula-Cookbook

or maybe you want to overload `patch` that it would by default `chdir` to source dir of pecl source?

**Review by kabel — APPROVED** [review]

**Comment by glensc** [comment]
@kabel I explicitly set `make -j1`, so make is deparalized but `make install` is still parallel. minor knit.

removed draft, so can be merged

**Comment by kabel** [comment]
Rebase merged at 37b6137f44a0ae579ba044254181f1587f5f2113

**Pull request closed without merging**
